from divisor_master import *

print('проверка числа на простоту')
print(1,check_simple(1))
print(2,check_simple(2))
print(3,check_simple(3))
print(4,check_simple(4))
print(5,check_simple(5))
print(6,check_simple(6))
print(7,check_simple(7))

print('\nссписок всех делителей числа')
print(1,getDilimiters(1))
print(2,getDilimiters(2))
print(3,getDilimiters(3))
print(4,getDilimiters(4))
print(5,getDilimiters(5))
print(8,getDilimiters(8))
print(12,getDilimiters(12))

print('\nсамый большой простой делитель числа')
print(1,getSimpleBiggestDelimiter(1))
print(2,getSimpleBiggestDelimiter(2))
print(3,getSimpleBiggestDelimiter(3))
print(5,getSimpleBiggestDelimiter(5))
print(14,getSimpleBiggestDelimiter(14))
print(12,getSimpleBiggestDelimiter(12))
print(20,getSimpleBiggestDelimiter(20))
print(22,getSimpleBiggestDelimiter(22))

print('\nканоническое разложение числа на простые множители')
print(78, getCanonicalDilimitersList(78))
print(1, getCanonicalDilimitersList(1))
print(3, getCanonicalDilimitersList(3))
print(4, getCanonicalDilimitersList(4))
print(11, getCanonicalDilimitersList(11))
print(83006, getCanonicalDilimitersList(83006))
print(897924289, getCanonicalDilimitersList(897924289))

print('\nсамый большой делитель')
print(78, getBiggestDelimiter(78))
print(77, getBiggestDelimiter(77))
print(44, getBiggestDelimiter(44))
print(4, getBiggestDelimiter(4))
