from divisor_master import *
print(1,check_simple(1))
print(2,check_simple(2))
print(3,check_simple(3))
print(4,check_simple(4))
print(5,check_simple(5))
print(6,check_simple(6))
print(7,check_simple(7))

print(1,getDilimiters(1))
print(2,getDilimiters(2))
print(3,getDilimiters(3))
print(4,getDilimiters(4))
print(5,getDilimiters(5))
print(8,getDilimiters(8))
print(12,getDilimiters(12))
